# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'PayPal-iOS-SDK', '~> 2.11.1'

target 'ninakendosa' do

end

target 'ninakendosaTests' do

end

target 'ninakendosaUITests' do

end

